### ISSUE TITLE
Add config to remove @babel/plugin-transform-runtime in testing

### ISSUE THREAD

**Issue by Nayshlok** [WTW-IM/babel-preset-wtw-im#20]
Downstream we are having to hack around this, so lets add a config to make it removable in the preset itself.

**Comment by aabenoja** [comment]
Spiked out the above PR. Checking for a `disableTransformRuntime` property on the `env` object doesn't pose any conflicts with `@babel/preset-env` and seems to make sense, but it may be better to have the proposed property live on the top level of the config object.

It might also be better to follow the existing pattern of `if (property !== false)` and rename the proposed property accordingly.
